### ISSUE TITLE
Syntax error when "!" exclamation mark in password

### ISSUE THREAD

**Issue by kplaczek** [3amprogrammer/knp-downloader#1]
I have password that contains exclamation mark (!) at the end and I get following error while I try to use the script.

` knpuniversity.ERROR: syntax error, unexpected '!' in C:\xampp\htdocs\knp-downloader-master\src/local.ini on line 2`

**Comment by 3amprogrammer** [comment]
According to [this](http://stackoverflow.com/questions/6684800/syntax-error-using-parse-ini-file-when-files-values-contain-exclamation-poin) to wrap your password with either double or single quotes.

**Comment by kplaczek** [comment]
This fixed the issue. Thanks.
